name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Recommended OpenJDK distribution
        java-version: '11'

    - name: Build and Run Tests
      run: |
        mvn clean test | tee test-results.log

    - name: Display Test Results (Pass/Fail)
      run: |
        echo "✅ Passed Tests:"
        grep "\[INFO\] Tests run: " test-results.log | grep ", Failures: 0, Errors: 0" || echo "No tests passed."

        echo "❌ Failed Tests:"
        grep "\[ERROR\]" test-results.log || echo "No tests failed."

    - name: Upload Test Results (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.log
